"""Generate the messages.po file with all translations (including Round 7 fixes)."""
import os

# Translation map: English -> Chinese
# This includes ALL Round 1-7 fixes
TRANSLATIONS = {
    # Common UI
    "Desktop": "桌面",
    "Terminal": "终端",
    "SSH Connection": "SSH 连接",
    "Command": "命令",
    "Password": "密码",
    "Copy": "复制",
    "Send": "发送",
    "Cancel": "取消",
    "Save": "保存",
    "Close": "关闭",
    "Update": "更新",
    "Reload": "重新加载",
    "Yes": "是",
    "No": "否",
    "OK": "确定",
    "Success": "成功",
    "Error": "错误",
    "Failed": "失败",
    "Image": "镜像",
    "Status": "状态",
    "Enabled": "已启用",
    "Sessions": "会话数",
    "Actions": "操作",
    "Weight": "权重",
    "Context": "上下文",
    "User": "用户",
    "Time": "时间",
    "Total": "总计",
    "Prev": "上一页",
    "Next": "下一页",
    "Delete": "删除",
    "Test": "测试",
    "Edit": "编辑",
    "Import": "导入",
    "Imported": "已导入",
    "Scan": "扫描",
    "Scanning...": "扫描中...",
    "Missing": "缺失",
    "Available": "可用",

    # User page (remote_desktop.html)
    "Remote Desktop Unavailable": "远程桌面不可用",
    "This feature has been disabled by an administrator. Check back later.": "此功能已被管理员禁用，请稍后再来。",
    "Verify Your Email": "验证您的邮箱",
    "You need to verify your email address before you can access Remote Desktop.": "您需要先验证邮箱才能访问远程桌面。",
    "Verify Email": "验证邮箱",
    "Run this in a terminal on your machine (not inside the desktop)": "在您自己的终端中运行此命令（不要在桌面内运行）",
    "Time remaining in session": "会话剩余时间",
    "Add more time to your session": "为会话延长更多时间",
    "Extend": "延长",
    "End session, all work will be lost": "结束会话，所有工作将丢失",
    "Stop": "停止",
    "Full graphical desktop for GUI tools": "用于 GUI 工具的完整图形桌面",
    "Browser-based shell, lighter than full desktop": "基于浏览器的 shell，比完整桌面更轻量",
    "Connect from your own terminal": "从您自己的终端连接",
    "Report a bug or feature request": "报告 bug 或功能请求",
    "Fullscreen": "全屏",
    "No Active Session": "无活动会话",
    "Launch an on-demand environment with preloaded tools": "启动一个预装工具的按需环境",
    "This is an ephemeral environment, nothing is saved between sessions.": "这是一个临时环境，会话之间不会保存任何内容。",
    "Avoid logging into anything sensitive.": "避免登录任何敏感账户或系统。",
    "If something breaks, just stop and start a new session.": "如果出现问题，只需停止并启动新会话即可。",
    "Desktop, Terminal, and SSH modes available from the bottom bar once your session starts.": "会话启动后，可从底部栏切换桌面、终端和 SSH 模式。",
    "Sessions expire after a set time to save resources and keep your environment fresh.": "会话将在设定时间后过期以节省资源并保持环境始终如新。",
    "Start Remote Desktop": "启动远程桌面",
    "Something went wrong on our end, please try again later or contact an administrator.": "服务器出现问题，请稍后重试或联系管理员。",
    "unknown": "未知",
    "at": "于",
    "unknown error": "未知错误",
    "All": "全部",
    "extensions used": "次延长已用完",
    "used": "已用",
    "session timed out": "会话超时",
    "Loading...": "加载中...",
    "Creating container...": "正在创建容器...",
    "Starting...": "启动中...",
    "Stopping...": "停止中...",
    "Adding...": "延长中...",
    "Sending...": "发送中...",
    "Are you sure you want to stop your session?": "确定要停止会话吗？",
    "Your session will expire in less than 5 minutes. Consider extending your session.": "您的会话将在 5 分钟内过期，请考虑延长会话时间。",
    "request failed": "请求失败",
    "Describe the bug or feature.\n\n": "描述 bug 或功能。\n\n",
    "For bugs: what were you doing, what happened, what did you expect? ": "对于 bug：您在做什么？发生了什么？您期望的结果是什么？",
    "If visual, paste an image link (imgur, 0x0.st).": "如果是视觉问题，请粘贴图片链接（imgur、0x0.st）。",
    "Thanks for your feedback!": "感谢您的反馈！",
    "Type something to send": "请输入内容后再发送",
    "Failed to send": "发送失败",
    "Network error": "网络错误",

    # Config page (remote_desktop_config.html)
    "Remote Desktop Enabled": "启用远程桌面",
    "When disabled, users cannot access the remote desktop page or create new sessions": "禁用后，用户无法访问远程桌面页面或创建新会话",
    "Require Verified Email": "需要验证邮箱",
    "Only allow verified users to access remote desktop. Has no effect unless email verification is enabled in CTFd settings.": "仅允许已验证的用户访问远程桌面。除非在 CTFd 设置中启用了邮箱验证，否则此选项无效。",
    "Command Logging": "命令日志",
    "Log shell commands run inside desktop sessions for research analytics. Requires a container image with telemetry hooks installed.": "记录桌面会话中运行的 shell 命令以用于研究分析。需要安装了遥测钩子的容器镜像。",
    "Container": "容器",
    "Docker Image": "Docker 镜像",
    "Memory Limit": "内存限制",
    "SHM Size": "共享内存大小",
    "Resolution": "分辨率",
    "CPU Limit": "CPU 限制",
    "Username Source": "用户名来源",
    "CTFd Display Name": "CTFd 显示名",
    "Email (before @)": "邮箱（@ 之前部分）",
    "Cap Drop": "丢弃 Cap",
    "Cap Add": "添加 Cap",
    "Session Timers": "会话计时器",
    "Initial Duration": "初始时长",
    "Extension Duration": "延长时长",
    "Max Extensions": "最大延长次数",
    "Timeouts": "超时设置",
    "VNC Ready Attempts": "VNC 就绪检测次数",
    "HTTP Timeout (seconds)": "HTTP 超时（秒）",
    "Cleanup Interval (seconds)": "清理间隔（秒）",
    "Docker Contexts": "Docker 上下文",
    "Import Contexts": "导入上下文",
    "Context Name": "上下文名称",
    "Public Hostname": "公开主机名",
    "Hostname (SSH)": "主机名（SSH）",
    "SSH target for remote hosts, leave blank if a matching docker context exists on the host": "远程主机的 SSH 目标，如果主机上存在匹配的 docker 上下文则留空",
    "Address users use to connect to VNC sessions on this host": "用户连接此主机上 VNC 会话使用的地址",
    "Higher weight means more sessions are scheduled to this context": "权重越高，调度到此上下文的会话越多",
    "Image Availability": "镜像可用性",
    "Click Scan to check image availability across contexts": "点击扫描以检查各上下文的镜像可用性",
    "Click Scan to check image availability": "点击扫描以检查镜像可用性",
    "No scan data yet. Click Scan to check image availability.": "暂无扫描数据。点击扫描以检查镜像可用性。",
    "No image configured": "未配置镜像",
    "No contexts configured": "未配置上下文",
    "No connected contexts": "无已连接的上下文",
    "Danger Zone": "危险区域",
    "Clear Session History": "清除会话历史",
    "Edit Docker Context": "编辑 Docker 上下文",
    "Import Docker Contexts": "导入 Docker 上下文",
    "Docker contexts detected from": "从此处检测到的 Docker 上下文：",
    "on this host. Set the public hostname for each context you want to use, this is the address users connect to for VNC sessions. You can adjust weight and other settings after importing.": "在此主机上。为每个要使用的上下文设置公开主机名，这是用户连接 VNC 会话使用的地址。导入后可以调整权重和其他设置。",
    "Scanning for contexts...": "正在扫描上下文...",
    "No new Docker contexts found on this host": "在此主机上未找到新的 Docker 上下文",
    "Make sure": "请确保",
    "is mounted and contexts are created with": "已挂载，且上下文已使用以下命令创建：",
    "DISABLED": "已禁用",
    "UP": "在线",
    "NO IMAGE": "无镜像",
    "DOWN": "离线",
    "Public hostname is required": "公开主机名为必填项",
    "Test Passed": "测试通过",
    "Test Failed": "测试失败",
    "Settings saved": "设置已保存",
    "Save failed": "保存失败",
    "Delete failed": "删除失败",
    "Import failed": "导入失败",
    "Update failed": "更新失败",
    "Reload failed": "重新加载失败",
    "Contexts reloaded": "上下文已重新加载",
    "Unable to reach the local Docker socket. Make sure Docker is running and the socket is mounted.": "无法连接到本地 Docker 套接字。请确保 Docker 正在运行且套接字已挂载。",
    "Local Docker socket is reachable.": "本地 Docker 套接字可连接。",
    "is reachable and the configured image was found": "可连接且找到了配置的镜像",
    "could not reach context": "无法连接到上下文",
    ": request failed, check the logs for details": "：请求失败，请查看日志了解详情",
    "connected": "已连接",
    "unreachable": "不可连接",
    "reachable": "可连接",
    "Delete context \"": "删除上下文\"",
    "\"?": "\"？",
    "Clear all session history? This resets stats and charts.": "清除所有会话历史？这将重置统计和图表。",
    "Cleared ": "已清除 ",
    " sessions, ": " 个会话，",
    " command logs": " 条命令日志",
    "Last scanned: ": "上次扫描：",
    "Error: ": "错误：",
    "Not found. Build or load this image on this host.": "未找到。请在此主机上构建或加载此镜像。",
    "Newest build found across contexts. ": "在所有上下文中找到的最新构建。",
    "MB, built ": "MB，构建于 ",
    "Possibly outdated. This image is ": "可能已过时。此镜像为 ",
    "MB but the newest build is ": "MB，但最新构建为 ",
    "MB (": "MB（",
    "MB difference). Built ": "MB 差异）。构建于 ",
    ". Consider rebuilding.": "。建议重新构建。",
    "Size (": "大小（",
    "MB) is consistent with the newest build (": "MB）与最新构建一致（",
    "MB). Built ": "MB）。构建于 ",
    "missing": "缺失",
    "possibly outdated": "可能已过时",
    "built": "构建于",

    # Dashboard (remote_desktop_dashboard.html)
    "Remote Desktop Dashboard": "远程桌面仪表盘",
    "Active Now": "当前活动",
    "Total Sessions": "总会话数",
    "Total Hours": "总时长",
    "Avg Duration": "平均时长",
    "Peak Concurrent": "峰值并发",
    "Unique Users": "独立用户",
    "Contexts": "上下文",
    "Total Commands": "总命令数",
    "Unique Tools": "独立工具数",
    "Unique Commands": "独立命令数",
    "Active Sessions": "活动会话",
    "Activity": "活动",
    "Reports": "报告",
    "Usage Heatmap": "使用热力图",
    "Top Users": "用户排行",
    "Session Duration Distribution": "会话时长分布",
    "Session End Reasons": "会话结束原因",
    "Per-Host Breakdown": "按主机分布",
    "Command Logs": "命令日志",
    "Command Feed": "命令流",
    "Per-User Commands": "按用户统计命令",
    "Top Tools": "热门工具",
    "Command Activity": "命令活动",
    "Purge All": "清除全部",
    "Clear All": "清除全部",
    "Clear All Reports": "清除所有报告",
    "Delete every submitted report? This cannot be undone.": "删除所有已提交的报告？此操作无法撤销。",
    "Purge ALL active sessions? This cannot be undone.": "清除所有活动会话？此操作无法撤销。",
    "No activity yet": "暂无活动",
    "No reports yet": "暂无报告",
    "No commands yet": "暂无命令",
    "No active sessions": "无活动会话",
    "No command data": "无命令数据",
    "No commands": "无命令",
    "No data yet": "暂无数据",
    "Past Week": "最近一周",
    "Past Month": "最近一个月",
    "All Time": "所有时间",
    "Report from": "报告来自",
    "Command History:": "命令历史：",
    "Extends": "延长次数",
    "Event": "事件",
    "Details": "详情",
    "Message": "消息",
    "Exit": "退出码",
    "Avg/Session": "平均/会话",
    "Unique Tools": "独立工具数",
    "Duration": "时长",
    "CWD": "工作目录",
    "Monitor": "监控",
    "Kill": "终止",
    "Killed": "已终止",
    "session(s)": "个会话",
    "Kill failed": "终止失败",
    "Extend failed": "延长失败",
    "Purge failed": "清除失败",
    "VNC unavailable": "VNC 不可用",
    "Failed to open VNC (check popup blocker)": "无法打开 VNC（请检查弹窗拦截）",
    "Admin": "管理员",
    "Hidden": "已隐藏",
    "Banned": "已封禁",
    "ACTIVE": "活动",
    "STARTING": "启动中",
    "EXPIRED": "已过期",
    "EXPIRING": "即将过期",
    "Requested": "已请求",
    "Created": "已创建",
    "Destroyed": "已销毁",
    "Expired": "已过期",
    "Extended": "已延长",
    "extended": "已延长",
    "Orphan Reaped": "孤儿会话已回收",
    "Host Down": "主机下线",
    "Host Up": "主机上线",
    "sessions": "会话",
    "Uses": "使用次数",
    "uses": "使用次数",
    "commands": "命令",
    "errors": "错误",
    "total": "总计",
    "active": "活动",
    "score": "评分",
    "unhealthy": "不健康",
    "image": "镜像",
    "age": "年龄",
    "leftover with no db row": "无数据库记录的残留",
    "purged": "已清除",
    "killed": "已终止",
    "monitoring": "监控中",
    "cleared": "已清除",
    "ext": "次延长",
    "cmds": "条命令",
    "extensions": "次延长",
    "Showing": "显示",
    "of": "/",
    "User ": "用户 ",
    "unavailable": "不可用",
    "'s session": "的会话",
    "'s session?": "的会话？",

    # Event descriptions / tooltips
    "Active sessions: how many desktops are running right now, where, and how long they have left.": "活动会话：当前正在运行的桌面数量、位置以及剩余时间。",
    "Recent session lifecycle events (create, extend, destroy, expire) across all users.": "所有用户的近期会话生命周期事件（创建、延长、销毁、过期）。",
    "Bug reports and feature requests submitted by users from the remote desktop bottom bar. Click a row to view the full message.": "用户从远程桌面底部栏提交的 bug 报告和功能请求。点击行查看完整消息。",
    "Session starts by hour and day of week. Spot peak usage windows for capacity planning.": "按小时和星期统计的会话启动数。用于容量规划的高峰使用窗口识别。",
    "Ranked by total desktop time. Identify power users or accounts consuming disproportionate resources.": "按总桌面时间排名。用于识别重度用户或消耗过多资源的账户。",
    "How long sessions lasted before ending. A left-skewed distribution means users leave quickly; a right-skewed one means they stay engaged.": "会话结束前的持续时长。左偏分布表示用户快速离开；右偏分布表示用户保持参与。",
    "Why sessions ended: expired, user-closed, or admin-killed. A high expired count means users may need longer timers or more extensions.": "会话结束原因：过期、用户关闭或管理员终止。高过期数表示用户可能需要更长的计时器或更多延长次数。",
    "Sessions, hours, and commands broken down by Docker host.": "按 Docker 主机划分的会话、时长和命令统计。",
    "Most-used shell tools across all sessions. Useful for evaluating which tools to preinstall in future images.": "所有会话中最常用的 shell 工具。用于评估未来镜像中应预装哪些工具。",
    "Command volume by hour and day of week. Spot peak shell-usage windows or correlate clusters with competition events.": "按小时和星期统计的命令量。发现高峰 shell 使用时段或将活动聚集与比赛事件关联。",
    "Live feed of shell commands from active sessions. Useful for monitoring what users are doing in real time.": "活动会话中 shell 命令的实时流。用于实时监控用户操作。",
    "Per-user command counts and their favorite tools.": "按用户统计的命令数及其常用工具。",
    "The Docker image used to create each desktop session. Change this if you have a custom image with specific tools or software pre-installed.": "用于创建每个桌面会话的 Docker 镜像。如果您有预装特定工具或软件的自定义镜像，请修改此项。",
    "Maximum RAM each desktop can use (e.g. 512m, 1g). Increase if users run memory-heavy applications, decrease to fit more desktops on one server.": "每个桌面可使用的最大内存（例如 512m、1g）。如果用户运行内存密集型应用请增加；要在单台服务器上运行更多桌面请减少。",
    "Shared memory available to the desktop (e.g. 256m). Browsers and GUI apps use this for rendering. If users see crashes or blank screens, try increasing it.": "桌面可用的共享内存（例如 256m）。浏览器和 GUI 应用使用它进行渲染。如果用户遇到崩溃或空白屏幕，请尝试增加此值。",
    "Screen resolution of the remote desktop (e.g. 1280x720). Higher values give more screen space but use more bandwidth and memory.": "远程桌面的屏幕分辨率（例如 1280x720）。值越大屏幕空间越多，但会占用更多带宽和内存。",
    "Maximum CPU cores each desktop can use (e.g. 1.0 = one core, 0.5 = half a core). Lower values let you run more desktops per server, higher values give users a snappier experience.": "每个桌面可使用的最大 CPU 核心数（例如 1.0 = 一个核心，0.5 = 半个核心）。值越低每台服务器可运行的桌面越多；值越高用户体验越流畅。",
    "Where to pull the Linux username inside the desktop. Normalized to lowercase letters and numbers, falls back to user{id} if the result is empty.": "在桌面中使用的 Linux 用户名来源。会规范化为小写字母和数字，结果为空时回退为 user{id}。",
    "Linux capabilities to drop from containers, comma-separated. Use ALL to drop everything then selectively add back with Cap Add. Changes only affect new sessions.": "要从容器中丢弃的 Linux capabilities，以逗号分隔。使用 ALL 丢弃全部，然后通过 Cap Add 选择性添加。更改仅影响新会话。",
    "Linux capabilities to add to containers, comma-separated. These are granted on top of whatever remains after Cap Drop. Must include caps matching any file capabilities on binaries in the image (e.g. nmap needs NET_RAW, NET_ADMIN, NET_BIND_SERVICE) or those binaries won't be executable. Changes only affect new sessions.": "要添加到容器的 Linux capabilities，以逗号分隔。这些将在 Cap Drop 丢弃后剩余权限的基础上授予。必须包含与镜像中二进制文件的文件权限匹配的 caps（例如 nmap 需要 NET_RAW、NET_ADMIN、NET_BIND_SERVICE），否则这些二进制文件将无法执行。更改仅影响新会话。",
    "How long a desktop session lasts before it expires. Users will see a countdown timer. Set higher for longer competitions, lower to save server resources.": "桌面会话在过期前的持续时长。用户将看到倒计时。长时间比赛请设置较高值，要节省服务器资源请设置较低值。",
    "How much extra time is added each time a user clicks Extend. Shorter values give users more control over how long they stay, longer values mean fewer clicks.": "每次用户点击\"延长\"时增加的额外时间。值越短用户对停留时间的控制越精细；值越长点击次数越少。",
    "How many times a user can extend their session. Set to 0 for no extensions (hard time limit). Higher values let users keep their desktop alive longer.": "用户可以延长会话的次数。设置为 0 表示不可延长（硬性时间限制）。值越高用户可以让桌面存活更久。",
    "How many times the server checks if a new desktop is ready before giving up. Increase if desktops fail to start on slower hardware.": "服务器在放弃前检查新桌面是否就绪的次数。如果桌面在较慢的硬件上启动失败请增加此值。",
    "How long to wait for a response from Docker when creating or managing desktops. Increase if you see timeout errors on slow networks.": "创建或管理桌面时等待 Docker 响应的时间。如果在慢速网络上遇到超时错误请增加此值。",
    "How often the server checks for expired sessions to clean up. Lower values free resources faster, higher values reduce server load.": "服务器检查过期会话以清理的频率。值越低释放资源越快；值越高服务器负载越低。",
    "Each context is a Docker host that can run desktop sessions. Import contexts from your Docker configuration to spread load across servers. Sessions are distributed by weight.": "每个上下文是一个可以运行桌面会话的 Docker 主机。从 Docker 配置导入上下文以跨服务器分散负载。会话按权重分配。",

    # EXIT_CODE_LABELS values
    "success": "成功",
    "error": "错误",
    "builtin misuse": "内置命令误用",
    "usage error": "使用错误",
    "bad fd": "错误的文件描述符",
    "sigaction": "sigaction 错误",
    "unknown": "未知",
    "arg list too long": "参数列表过长",
    "exec format error": "执行格式错误",
    "bad executable": "错误的可执行文件",
    "no memory": "内存不足",
    "no perms": "无权限",
    "interrupted": "被中断",
    "i/o error": "I/O 错误",
    "no such device": "无此设备",
    "no such file": "无此文件",
    "no such process": "无此进程",
    "pipe": "管道错误",
    "symlink loop": "符号链接循环",
    "missing devfile": "缺失设备文件",
    "not a directory": "不是目录",
    "is a directory": "是目录",
    "invalid argument": "无效参数",
    "file table overflow": "文件表溢出",
    "too many files": "文件过多",
    "inappropriate ioctl": "不适当的 ioctl",
    "text file busy": "文本文件忙",
    "file too large": "文件过大",
    "no space": "空间不足",
    "illegal seek": "非法 seek",
    "read-only fs": "只读文件系统",
    "too many links": "链接过多",
    "broken pipe": "管道破裂",
    "math argument": "数学参数",
    "result too large": "结果过大",
    "no resource": "资源不足",
    "deadlock": "死锁",
    "name too long": "名称过长",
    "no locks": "无锁",
    "empty": "空",
    "not empty": "非空",
    "quota": "配额超限",
    "no media": "无介质",
    "net": "网络错误",
    "custom": "自定义",
    "not executable": "不可执行",
    "command not found": "命令未找到",
    "invalid exit arg": "无效的退出参数",
    "hangup": "挂断",
    "ctrl-c": "Ctrl-C 中断",
    "ctrl-z": "Ctrl-Z 暂停",
    "quit (core dump)": "退出（核心转储）",
    "illegal instruction": "非法指令",
    "trap": "陷阱",
    "abort": "中止",
    "misaligned": "未对齐",
    "bus error": "总线错误",
    "fpe": "浮点异常",
    "kill": "被杀死",
    "usr1": "用户信号 1",
    "segfault": "段错误",
    "usr2": "用户信号 2",
    "alarm timeout": "闹钟超时",
    "term": "被终止",
    "stkflt": "栈错误",
    "child": "子进程退出",
    "continued": "已继续",
    "stopped": "已停止",
    "tstp": "终端停止",
    "ttin": "后台读 tty",
    "ttou": "后台写 tty",
    "urg": "紧急数据",
    "xcpu": "CPU 超限",
    "xfsz": "文件大小超限",
    "vtalrm": "虚拟定时器",
    "prof": "性能分析定时器",
    "winch": "窗口大小变化",
    "io": "I/O 就绪",
    "pwr": "电源故障",
    "sys": "系统调用",
    "file size exceeded": "文件大小超限",
    "bad syscall": "错误的系统调用",
    "exit out of range": "退出码超出范围",
    "signal": "信号",

    # Other misc strings from dashboard
    "os error": "操作系统错误",
    "temp failure": "临时失败",
    "internal error": "内部错误",
    "data error": "数据错误",
    "config error": "配置错误",
    "permission denied": "权限被拒绝",
    "host not found": "主机未找到",
    "user not found": "用户未找到",
    "input not found": "输入未找到",
    "cpu time exceeded": "CPU 时间超限",
    "apt broken packages": "apt 损坏的包",
    "apt error": "apt 错误",
    "bg read from tty": "后台读 tty",
    "bg write to tty": "后台写 tty",
    "breakpoint trap": "断点陷阱",
    "can't create output": "无法创建输出",
    "aborted": "已中止",
    "floating point error": "浮点错误",
    "child exited": "子进程退出",

    # Separators
    ", ": "，",
    ". ": "。",
    ": ": "：",
    "?": "？",

    # Additional strings from dashboard
    "Rank": "排名",
    "Host": "主机",
    "Count": "次数",
    "Tool": "工具",
    "Last Used": "最后使用",
    "Username": "用户名",
    "Created At": "创建时间",
    "Started": "已启动",
    "End Reason": "结束原因",
    "Command Count": "命令数",
    "Top Tools": "热门工具",
    "Session Count": "会话数",
    "Avg Commands": "平均命令数",
    "Favorites": "收藏",
    "Avg Duration (min)": "平均时长（分钟）",
    "Max Concurrent": "最大并发",
    "Sessions/Hour": "会话/小时",
    "Hour": "小时",
    "Day": "天",
    "Weekday": "星期",
    "Hour of Day": "小时",
    "Sessions Started": "已启动会话数",
    "Session ID": "会话 ID",
    "Started At": "启动时间",
    "Ended At": "结束时间",
    "Container ID": "容器 ID",
    "Docker Context": "Docker 上下文",
    "Report ID": "报告 ID",
    "Submitted At": "提交时间",
    "View": "查看",

    # Additional missing strings
    "Time Remaining": "剩余时间",
    "Public hostname": "公开主机名",
    "command logs": "命令日志",
    "killed (OOM?)": "已杀死（内存不足？）",
    "stack fault": "栈错误",
    "terminated": "已终止",
    "user signal 1": "用户信号 1",
    "user signal 2": "用户信号 2",
    " is reachable and the configured image was found": "可连接且找到了配置的镜像",
    "Command counts and activity by user. Click the total to see their full history.": "按用户统计的命令数和活动。点击总数查看完整历史。",
    "Currently running desktop containers. Kill or extend individual sessions, or purge all at once during incidents.": "当前正在运行的桌面容器。可以终止或延长单个会话，或在事件发生时一次性清除全部。",
    "How long sessions typically last. If most are very short, your timeout may be too aggressive. If most hit the max, users probably need more time.": "会话的典型持续时长。如果大多数很短，说明超时设置可能过于激进。如果大多数达到上限，用户可能需要更多时间。",
    "Most-used command line tools across all sessions. See what software participants actually reach for and whether your image has the right tooling.": "所有会话中最常用的命令行工具。了解参赛者实际使用哪些软件，以及您的镜像是否包含合适的工具。",
    "Real-time event stream. Session lifecycle, admin actions, and host health changes as they happen. Useful for catching errors during a live competition.": "实时事件流。会话生命周期、管理员操作和主机健康状态变化的即时记录。适用于在比赛进行中捕获错误。",
    "Recent shell commands from all sessions. Spot-check what participants are running or investigate suspicious activity.": "所有会话的近期 shell 命令。抽查参赛者正在运行的内容或调查可疑活动。",
    "Session distribution across Docker hosts. Check if load balancing weights are working or if one host is taking all the traffic.": "跨 Docker 主机的会话分布。检查负载均衡权重是否生效，或某台主机是否承担了全部流量。",
    "Shows whether the configured Docker image is present on each context. Hover icons for hash, size, and build time. Pull or rebuild images on hosts marked as missing or outdated.": "显示配置的 Docker 镜像是否存在于每个上下文。将鼠标悬停在图标上查看哈希、大小和构建时间。在标记为缺失或过时的主机上拉取或重新构建镜像。",
    "Unable to reach the local Docker socket. Make sure <code>/var/run/docker.sock</code> is mounted and the container has the right group permissions (<code>group_add</code>). See the Docker access section in the README.": "无法连接到本地 Docker 套接字。请确保已挂载 <code>/var/run/docker.sock</code>，且容器具有正确的组权限（<code>group_add</code>）。请参阅 README 中的 Docker 访问部分。",
}

# Generate .po file content
header = '''msgid ""
msgstr ""
"Project-Id-Version: CTFd Remote Desktop Plugin 1.0\\n"
"POT-Creation-Date: 2026-07-20 00:00+0800\\n"
"Language: zh_Hans_CN\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=1; plural=0;\\n"

'''

def escape(s):
    """Escape string for .po format."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t')

lines = [header]
for en, zh in sorted(TRANSLATIONS.items(), key=lambda x: x[0].lower()):
    lines.append(f'msgid "{escape(en)}"')
    lines.append(f'msgstr "{escape(zh)}"')
    lines.append('')

content = '\n'.join(lines)
print(f"Generated {len(TRANSLATIONS)} translation entries")
print(f"Content length: {len(content)} chars")
